import fs from 'node:fs/promises';
import path from 'node:path';
import { BLOG_POSTS } from '@/generated/blog-data.ts';
import { POLICIES } from '@/generated/static-content-data.ts';
import { type SearchResult, STATIC_SEARCH_PAGES } from '@/lib/search.ts';

const GENERATED_OUTPUT_PATH = path.join(process.cwd(), 'src', 'generated', 'search-data.ts');

async function generateSearchData(): Promise<void> {
	const results: SearchResult[] = [
		...STATIC_SEARCH_PAGES,
		...BLOG_POSTS.map(
			(post): SearchResult => ({
				title: post.title,
				description: post.description || 'Read our latest blog post.',
				url: `/blog/${post.slug}`,
				category: 'Blog',
				type: 'Article',
			})
		),
		...POLICIES.map(
			(policy): SearchResult => ({
				title: policy.title,
				description: policy.description || 'Legal document.',
				url: `/policies/${policy.slug}`,
				category: 'Policy',
				type: 'Legal',
			})
		),
	];

	const fileContents = `/* eslint-disable */
// This file is auto-generated by scripts/generate_search_data.ts.
// Do not edit by hand.

import type { SearchResult } from '@/lib/search';

export const SEARCH_DATA: SearchResult[] = ${JSON.stringify(results, null, 2)};
`;

	await fs.mkdir(path.dirname(GENERATED_OUTPUT_PATH), { recursive: true });
	await fs.writeFile(GENERATED_OUTPUT_PATH, fileContents, 'utf8');
}

try {
	await generateSearchData();
	console.log('Generated static search data.');
} catch (error) {
	console.error('Failed to generate static search data.');
	throw error;
}
